backend:
  name: github
  repo: goosebearingbashshell/goosebearingbashshell.github.io
  branch: master

publish_mode: editorial_workflow

media_folder: "assets/images"

collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string", required: false}
      - {label: "Author", name: "author", widget: "string", required: false}
      - {label: "Twitter Card", name: "image", widget: "image", required: false}
      - {label: "Text", name: "body", widget: "markdown", required: false}
  - name: "pages"
    label: "Pages"
    folder: "_pages"
    create: true
    slug: "{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string", required: false}
      - {label: "Auteur", name: "author", widget: "string", required: false}
      - {label: "Twitter Card", name: "image", widget: "image", required: false}
      - {label: "Texte", name: "body", widget: "markdown", required: false}
